### ISSUE TITLE
Use iframe instead of document.body.ele

### ISSUE THREAD

**Issue by hisakaz0** [pinkienort/AutoScrolling#103]
**purpose**
- unite modal option UI in all window
- prevent to break modal option window

**solution**
- Use iframe instead of document.body.el

**concern**
- need to communication with `window`s 

**todo(checklist)**
- [ ] check how to communicate with `widnow` objects
- [ ] edit manifest.json
- [ ] impl content/some scripts
