### ISSUE TITLE
refactor: modulaize the function, and classes 

### ISSUE THREAD

**Issue by hisakaz0** [pinkienort/AutoScrolling#28]
### purpose
- Make testable codes
- Use the same functions and classes in anywhere

**Comment by hisakaz0** [comment]
#### Plant to replace
- Take the option script firstly, and then, content script, background script.
- Following is detail how to replace.

1. Make modules from the functions in the script
2. Test the modules 
3. Replace the script

**Comment by hisakaz0** [comment]
#### todo
- [x] Install test env for units
- [x] Replace the option script
- [ ] Replace the content script 
- [ ] Replace the background script
